version: '3'

services:
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
#      - ./locale:/code/locale
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A translation_template worker --loglevel=info
    volumes:
      - ./:/code
    depends_on:
      - redis
      - backend

